#!/bin/bash

DOTFILES_GITHUB="https://github.com/ababup1192/dotfiles.git"; export DOTFILES_GITHUB
DOTPATH=~/.dotfiles; export DOTPATH

dotfiles_download() {
    echo "Download dotfiles"
    git clone --recursive "$DOTFILES_GITHUB" "$DOTPATH"
}

dotfiles_deploy() {
    cd "$DOTPATH"
    make deploy
}

dotfiles_install() {
    dotfiles_download &&
        dotfiles_deploy
}

dotfiles_install
