#!/bin/bash

DOTPATH=~/.dotfiles; export DOTPATH

dotfiles_download() {
    local tarball="https://codeload.github.com/ababup1192/dotfiles/tar.gz/master"
    echo "Download dotfiles"
    curl "$tarball" | tar zx
    mv -f dotfiles-master "$DOTPATH"
}

dotfiles_deploy() {
    cd "$DOTPATH"
    make deploy
}

dotfiles_install() {
    dotfiles_download &&
        dotfiles_deploy
}

dotfiles_install
