#!/bin/bash

DOTFILES_GITHUB="git@github.com:ababup1192/dotfiles.git"; export DOTFILES_GITHUB
DOTPATH=~/.dotfiles; export DOTPATH

dotfiles_download() {
    echo "Download dotfiles"
    git clone --recursive "$DOTFILES_GITHUB" "$DOTPATH"
}

zplug_download() {
    ZPLUG_HOME=~/.zplug; export ZPLUG_HOME
    git clone https://github.com/zplug/zplug $ZPLUG_HOME
}

dotfiles_deploy() {
    cd "$DOTPATH"
    make deploy
}

dotfiles_install() {
    dotfiles_download &&
        zplug_download &&
        dotfiles_deploy
}

dotfiles_install
